services:
  stori-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stori-transaction-processor
    environment:
      # Database configuration (using SQLite)
      - DB_DRIVER=sqlite
      - DATA_PATH=/app/data
      
      # Hybrid Email Configuration
      - EMAIL_MODE=development  # Options: development (MailHog), gmail (real Gmail)
      
      # MailHog Configuration (development mode)
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
      
      # Gmail Configuration (for switching to real emails)
      - GMAIL_HOST=smtp.gmail.com
      - GMAIL_PORT=587
      - GMAIL_USERNAME=${GMAIL_USERNAME:-your-email@gmail.com}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD:-your-app-password}
      
      # General Email Configuration
      - FROM_ADDRESS=noreply@stori.com
      - FROM_NAME=Stori Account Summary
      - TO_ADDRESS=${TO_ADDRESS:-test@example.com}
      - TO_NAME=${TO_NAME:-Test User}
      
      - LOG_LEVEL=info
      
      - MAX_FILE_SIZE=10485760
      - MAX_TRANSACTIONS=100000
    volumes:
      - ./testdata:/app/data:ro
      - ./data:/app/db
    depends_on:
      - mailhog
    networks:
      - stori-network
    restart: no

  mailhog:
    image: mailhog/mailhog:latest
    container_name: stori-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - stori-network
    restart: unless-stopped

networks:
  stori-network:
    driver: bridge